-- v3: Email template management
CREATE TABLE IF NOT EXISTS email_templates (
    id INT AUTO_INCREMENT PRIMARY KEY,
    template_name VARCHAR(120) NOT NULL UNIQUE,
    subject VARCHAR(255) NOT NULL,
    body LONGTEXT NOT NULL,
    variables TEXT NULL,
    status TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO email_templates (template_name, subject, body, variables, status)
VALUES
('appointment_confirmed',
 'Appointment Confirmed - {{clinic_name}}',
 '<!doctype html><html><body style="margin:0;padding:0;background-color:#f2f5f8;font-family:Arial,Helvetica,sans-serif;"><table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="background-color:#f2f5f8;margin:0;padding:0;"><tr><td align="center" style="padding:20px 10px;"><table role="presentation" cellpadding="0" cellspacing="0" border="0" width="600" style="width:100%;max-width:600px;background-color:#ffffff;border-radius:12px;overflow:hidden;"><tr><td style="padding:14px 20px;background-color:#0f6f90;color:#ffffff;font-size:18px;font-weight:bold;">JMedi Smart Medical Platform</td></tr><tr><td><table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%"><tr><td width="60%" valign="top" style="width:60%;padding:26px 22px;background-color:#eef4f7;"><div style="font-size:30px;line-height:34px;color:#0f7288;font-weight:800;letter-spacing:0.5px;margin-bottom:14px;">Appointment Confirmed</div><div style="font-size:28px;line-height:36px;color:#1f2d3d;margin-bottom:14px;">Dear {{patient_name}},</div><div style="font-size:22px;line-height:34px;color:#1f2d3d;margin-bottom:18px;">Your appointment with <strong>{{doctor_name}}</strong> has been confirmed.</div><table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="background-color:#e9eef3;border-radius:8px;"><tr><td style="padding:15px;border-radius:8px;"><div style="font-size:34px;line-height:40px;color:#1f2d3d;"><strong>Date:</strong> {{appointment_date}}</div><div style="font-size:34px;line-height:40px;color:#1f2d3d;margin-top:6px;"><strong>Time:</strong> {{appointment_time}}</div></td></tr></table><div style="font-size:22px;line-height:34px;color:#1f2d3d;margin-top:18px;">Thank you,<br>{{clinic_name}}</div></td><td width="40%" valign="middle" align="center" style="width:40%;padding:26px 14px;background-color:#1fa2a6;"><table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="max-width:220px;background-color:#ffffff;border-radius:14px;"><tr><td align="center" style="padding:20px 12px 10px 12px;"><img src="{{clinic_logo}}" alt="{{clinic_name}} logo" width="120" style="display:block;border:0;outline:none;text-decoration:none;max-width:120px;height:auto;margin:0 auto 10px auto;"><div style="font-size:44px;line-height:48px;color:#0f4e75;font-weight:800;">JMedi</div><div style="font-size:16px;line-height:22px;color:#0f7288;">Smart Medical Platform</div></td></tr><tr><td align="center" style="padding:12px;background-color:#18828a;color:#ffffff;font-size:16px;line-height:20px;border-bottom-left-radius:14px;border-bottom-right-radius:14px;">Powered by JNVWeb</td></tr></table></td></tr></table></td></tr><tr><td align="center" style="padding:12px 16px;background-color:#f0f3f6;color:#667085;font-size:12px;line-height:18px;">&copy; {{year}} JMedi – Smart Medical Platform</td></tr></table></td></tr></table></body></html>',
 'patient_name,doctor_name,appointment_date,appointment_time,clinic_name,clinic_logo,year',
1),
('appointment_cancelled', 'Appointment Cancelled - {{clinic_name}}', '<div style="font-size:22px;line-height:30px;color:#b42318;font-weight:700;margin-bottom:8px;">Appointment Cancelled</div><div style="font-size:16px;line-height:24px;color:#1f2933;margin-bottom:12px;">Dear {{patient_name}},</div><div style="font-size:16px;line-height:24px;color:#1f2933;margin-bottom:14px;">Your appointment with <strong>{{doctor_name}}</strong> was cancelled. We apologize for the inconvenience.</div><table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="background:#fff4f2;border:1px solid #f3d4ce;border-radius:10px;margin:10px 0 14px 0;"><tr><td style="padding:12px 14px;"><div style="font-size:14px;line-height:20px;color:#5f6c7b;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:6px;">Original slot</div><div style="font-size:18px;line-height:26px;color:#1f2933;"><strong>Date:</strong> {{appointment_date}}</div><div style="font-size:18px;line-height:26px;color:#1f2933;margin-top:6px;"><strong>Time:</strong> {{appointment_time}}</div></td></tr></table><div style="font-size:16px;line-height:24px;color:#1f2933;margin-bottom:10px;">If you would like to reschedule, reply to this email or call our front desk and we will help you find the next available time.</div><div style="font-size:16px;line-height:24px;color:#1f2933;margin-top:14px;">Thank you,<br>{{clinic_name}}</div>', 'patient_name,doctor_name,appointment_date,appointment_time,clinic_name', 1),
('doctor_approved', 'Doctor Profile Approved - {{clinic_name}}', '<div style="font-size:22px;line-height:30px;color:#0f6f90;font-weight:700;margin-bottom:8px;">Profile Approved</div><div style="font-size:16px;line-height:24px;color:#1f2933;margin-bottom:12px;">Dear {{doctor_name}},</div><div style="font-size:16px;line-height:24px;color:#1f2933;margin-bottom:14px;">Your doctor profile is approved and now visible to patients on {{clinic_name}}.</div><div style="background:#f0f4ff;border:1px solid #d7e3ff;border-radius:10px;padding:12px 14px;margin-bottom:14px;"><div style="font-size:14px;line-height:20px;color:#4b5563;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:6px;">Next steps</div><div style="font-size:16px;line-height:24px;color:#1f2933;">- Keep your availability updated so patients can book instantly.</div><div style="font-size:16px;line-height:24px;color:#1f2933;">- Review your profile details and ensure contact information is correct.</div><div style="font-size:16px;line-height:24px;color:#1f2933;">- Respond promptly to new appointment requests and confirmations.</div></div><div style="font-size:16px;line-height:24px;color:#1f2933;margin-top:10px;">We are excited to have you onboard.</div><div style="font-size:16px;line-height:24px;color:#1f2933;margin-top:14px;">Regards,<br>{{clinic_name}}</div>', 'doctor_name,clinic_name', 1),
('payment_success', 'Payment Successful - {{clinic_name}}', '<div style="font-size:22px;line-height:30px;color:#0f6f90;font-weight:700;margin-bottom:8px;">Payment Received</div><div style="font-size:16px;line-height:24px;color:#1f2933;margin-bottom:12px;">Dear {{patient_name}},</div><div style="font-size:16px;line-height:24px;color:#1f2933;margin-bottom:14px;">We have successfully recorded your payment.</div><table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="background:#f2f7ff;border:1px solid #d7e3ff;border-radius:10px;margin:10px 0 14px 0;"><tr><td style="padding:12px 14px;"><div style="font-size:14px;line-height:20px;color:#4b5563;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:6px;">Receipt</div><div style="font-size:20px;line-height:28px;color:#0f6f90;font-weight:700;">Amount: {{amount}}</div></td></tr></table><div style="font-size:16px;line-height:24px;color:#1f2933;margin-bottom:10px;">This receipt has been saved to your records. If you need any assistance, reply to this email and our team will help.</div><div style="font-size:16px;line-height:24px;color:#1f2933;margin-top:14px;">Thank you,<br>{{clinic_name}}</div>', 'patient_name,amount,clinic_name', 1),
('patient_registration', 'Welcome to {{clinic_name}}', '<div style="font-size:22px;line-height:30px;color:#0f6f90;font-weight:700;margin-bottom:8px;">Welcome to {{clinic_name}}</div><div style="font-size:16px;line-height:24px;color:#1f2933;margin-bottom:12px;">Dear {{patient_name}},</div><div style="font-size:16px;line-height:24px;color:#1f2933;margin-bottom:14px;">Thank you for creating your account with {{clinic_name}}. You can now book appointments and manage your visits from one place.</div><div style="background:#f4f9f4;border:1px solid #d7ead7;border-radius:10px;padding:12px 14px;margin-bottom:14px;"><div style="font-size:14px;line-height:20px;color:#4b5563;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:6px;">What you can do</div><div style="font-size:16px;line-height:24px;color:#1f2933;">- Schedule or reschedule appointments online.</div><div style="font-size:16px;line-height:24px;color:#1f2933;">- Receive email updates about your visits.</div><div style="font-size:16px;line-height:24px;color:#1f2933;">- Keep your details up to date for faster check-in.</div></div><div style="font-size:16px;line-height:24px;color:#1f2933;margin-top:10px;">We look forward to seeing you soon.</div><div style="font-size:16px;line-height:24px;color:#1f2933;margin-top:14px;">Regards,<br>{{clinic_name}}</div>', 'patient_name,clinic_name', 1),
('password_reset', 'Password Reset Request - {{clinic_name}}', '<div style="font-size:22px;line-height:30px;color:#0f6f90;font-weight:700;margin-bottom:8px;">Reset Your Password</div><div style="font-size:16px;line-height:24px;color:#1f2933;margin-bottom:12px;">Hello {{patient_name}},</div><div style="font-size:16px;line-height:24px;color:#1f2933;margin-bottom:14px;">We received a request to reset the password for your {{clinic_name}} account.</div><div style="text-align:center;margin:14px 0 16px 0;"><a href="{{reset_link}}" style="background:#0f6f90;color:#ffffff;text-decoration:none;padding:12px 18px;border-radius:8px;font-size:16px;font-weight:600;display:inline-block;">Reset Password</a></div><div style="font-size:16px;line-height:24px;color:#1f2933;margin-bottom:10px;">If the button above does not work, copy and paste this link into your browser:</div><div style="font-size:14px;line-height:20px;color:#0f6f90;background:#f1f5f9;border:1px solid #d8e2ef;border-radius:8px;padding:10px 12px;word-break:break-all;">{{reset_link}}</div><div style="font-size:16px;line-height:24px;color:#1f2933;margin-top:14px;">If you did not request this change, you can ignore this email and your password will stay the same.</div><div style="font-size:16px;line-height:24px;color:#1f2933;margin-top:14px;">Regards,<br>{{clinic_name}}</div>', 'patient_name,reset_link,clinic_name', 1)
ON DUPLICATE KEY UPDATE
    subject = VALUES(subject),
    body = VALUES(body),
    variables = VALUES(variables),
    status = VALUES(status),
    updated_at = CURRENT_TIMESTAMP;
